version: '2'
services:

  memcached:
    image: memcached

  redis:
    image: redis:latest

  db:
    image: postgres:13.1
    environment:
      - POSTGRES_PASSWORD=postgres

  application:
    build: 
      context: .
    image: "socialsirius/demos:driver-licence-${VERSION}"
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - DATABASE_HOST=db
      - DJANGO_SETTINGS_MODULE=settings.develop
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    depends_on:
      - db
      - memcached
      - redis
